/**
 * @description Quick Action LWC on Opportunity (Renewal) that lets the user
 * create a Quote in one step by filling in just the insurance provider,
 * plan name, proposed premium, and description. The Quote.Name field is
 * auto-generated by the Apex controller, so users never have to type it.
 * Configured as a ScreenAction in the LWC meta — appears as a modal when
 * invoked from the Opportunity highlights actions.
 * @author Liam Jeong (liam.jeong@5sinfusion.com)
 * @date 2026-05-23
 */
import { LightningElement, api } from "lwc";
import { CloseActionScreenEvent } from "lightning/actions";
import { ShowToastEvent } from "lightning/platformShowToastEvent";
import { NavigationMixin } from "lightning/navigation";

import createQuote from "@salesforce/apex/QuoteCreateController.createQuote";

export default class QuickCreateQuote extends NavigationMixin(
	LightningElement
) {
	@api recordId;

	insuranceProviderId = null;
	planName = "";
	proposedPremium = null;
	description = "";

	isSubmitting = false;
	errorMessage = null;

	get providerFilter() {
		// Constrain the Account lookup to Insurance Provider record type.
		return {
			criteria: [
				{
					fieldPath: "RecordType.DeveloperName",
					operator: "eq",
					value: "Insurance_Provider"
				}
			]
		};
	}

	get submitLabel() {
		return this.isSubmitting ? "Creating..." : "Create Quote";
	}

	get isSubmitDisabled() {
		return this.isSubmitting || !this.insuranceProviderId;
	}

	handleProviderChange(event) {
		const ids = event.detail.recordId;
		this.insuranceProviderId = Array.isArray(ids) ? ids[0] : ids;
	}

	handlePlanNameChange(event) {
		this.planName = event.target.value;
	}

	handlePremiumChange(event) {
		const value = event.target.value;
		this.proposedPremium = value === "" ? null : parseFloat(value);
	}

	handleDescriptionChange(event) {
		this.description = event.target.value;
	}

	async handleSubmit() {
		this.errorMessage = null;
		if (!this.insuranceProviderId) {
			this.errorMessage = "Insurance Provider is required.";
			return;
		}
		this.isSubmitting = true;
		try {
			const result = await createQuote({
				opportunityId: this.recordId,
				insuranceProviderId: this.insuranceProviderId,
				planName: this.planName,
				proposedPremium: this.proposedPremium,
				description: this.description
			});
			this.toast(
				"Quote Created",
				`${result.quoteName} created successfully.`,
				"success"
			);
			this.closeAndNavigate(result.quoteId);
		} catch (error) {
			this.errorMessage = this.readError(error);
		} finally {
			this.isSubmitting = false;
		}
	}

	handleCancel() {
		this.dispatchEvent(new CloseActionScreenEvent());
	}

	closeAndNavigate(quoteId) {
		this.dispatchEvent(new CloseActionScreenEvent());
		this[NavigationMixin.Navigate]({
			type: "standard__recordPage",
			attributes: {
				recordId: quoteId,
				objectApiName: "Quote",
				actionName: "view"
			}
		});
	}

	readError(error) {
		if (error?.body?.message) return error.body.message;
		if (error?.message) return error.message;
		return "An unexpected error occurred.";
	}

	toast(title, message, variant) {
		this.dispatchEvent(
			new ShowToastEvent({ title, message, variant })
		);
	}
}
