/**
 * @description Quick Action LWC on Opportunity (Renewal) that lets the user
 * create a Quote in one step. Pre-fills Proposed Start Date and Term from
 * the Renewal's Original Insurance (end-date+1 and existing term), so the
 * agent only has to confirm or adjust those values plus pick a provider and
 * enter the premium. The Quote.Name field is auto-generated by the Apex
 * controller, so users never have to type it.
 * @author Liam Jeong (liam.jeong@5sinfusion.com)
 * @date 2026-05-23
 */
import { LightningElement, api, wire } from "lwc";
import { getRecord, getFieldValue } from "lightning/uiRecordApi";
import { CloseActionScreenEvent } from "lightning/actions";
import { ShowToastEvent } from "lightning/platformShowToastEvent";
import { NavigationMixin } from "lightning/navigation";

import ORIG_INS_END_DATE from "@salesforce/schema/Opportunity.Original_Insurance__r.Insurance_End_Date__c";
import ORIG_INS_TERM from "@salesforce/schema/Opportunity.Original_Insurance__r.Insurance_Term_months__c";

import createQuote from "@salesforce/apex/QuoteCreateController.createQuote";

const OPP_FIELDS = [ORIG_INS_END_DATE, ORIG_INS_TERM];

export default class QuickCreateQuote extends NavigationMixin(
	LightningElement
) {
	@api recordId;

	insuranceProviderId = null;
	planName = "";
	proposedPremium = null;
	proposedStartDate = null;
	proposedTerm = null;
	description = "";

	isSubmitting = false;
	errorMessage = null;

	/** Loads the parent Opportunity so we can pre-fill from the Original Insurance. */
	@wire(getRecord, { recordId: "$recordId", fields: OPP_FIELDS })
	wiredOpportunity({ data }) {
		if (!data) return;
		const endDate = getFieldValue(data, ORIG_INS_END_DATE);
		const term = getFieldValue(data, ORIG_INS_TERM);
		if (endDate && this.proposedStartDate == null) {
			this.proposedStartDate = this.addOneDay(endDate);
		}
		if (term != null && this.proposedTerm == null) {
			this.proposedTerm = term;
		}
	}

	get providerMatchingInfo() {
		return { primaryField: { fieldPath: "Name" } };
	}

	get providerDisplayInfo() {
		return { primaryField: "Name" };
	}

	get providerFilter() {
		// Server-side filter: only show Accounts with the Insurance Provider record type.
		return {
			criteria: [
				{
					fieldPath: "RecordType.DeveloperName",
					operator: "eq",
					value: "Insurance_Provider"
				}
			]
		};
	}

	get submitLabel() {
		return this.isSubmitting ? "Creating..." : "Create Quote";
	}

	get isSubmitDisabled() {
		return (
			this.isSubmitting ||
			!this.insuranceProviderId ||
			this.proposedPremium == null ||
			!this.proposedStartDate ||
			this.proposedTerm == null
		);
	}

	handleProviderChange(event) {
		const ids = event.detail.recordId;
		this.insuranceProviderId = Array.isArray(ids) ? ids[0] : ids;
	}

	handlePlanNameChange(event) {
		this.planName = event.target.value;
	}

	handlePremiumChange(event) {
		const value = event.target.value;
		this.proposedPremium = value === "" ? null : parseFloat(value);
	}

	handleStartDateChange(event) {
		this.proposedStartDate = event.target.value || null;
	}

	handleTermChange(event) {
		const value = event.target.value;
		this.proposedTerm = value === "" ? null : parseInt(value, 10);
	}

	handleDescriptionChange(event) {
		this.description = event.target.value;
	}

	async handleSubmit() {
		this.errorMessage = null;
		if (!this.insuranceProviderId) {
			this.errorMessage = "Insurance Provider is required.";
			return;
		}
		if (this.proposedPremium == null) {
			this.errorMessage = "Proposed Premium is required.";
			return;
		}
		if (!this.proposedStartDate) {
			this.errorMessage = "Proposed Start Date is required.";
			return;
		}
		if (this.proposedTerm == null) {
			this.errorMessage = "Proposed Term is required.";
			return;
		}
		this.isSubmitting = true;
		try {
			const result = await createQuote({
				opportunityId: this.recordId,
				insuranceProviderId: this.insuranceProviderId,
				planName: this.planName,
				proposedPremium: this.proposedPremium,
				proposedStartDate: this.proposedStartDate,
				proposedTerm: this.proposedTerm,
				description: this.description
			});
			this.toast(
				"Quote Created",
				`${result.quoteName} created successfully.`,
				"success"
			);
			this.closeAndNavigate(result.quoteId);
		} catch (error) {
			this.errorMessage = this.readError(error);
		} finally {
			this.isSubmitting = false;
		}
	}

	handleCancel() {
		this.dispatchEvent(new CloseActionScreenEvent());
	}

	closeAndNavigate(quoteId) {
		this.dispatchEvent(new CloseActionScreenEvent());
		this[NavigationMixin.Navigate]({
			type: "standard__recordPage",
			attributes: {
				recordId: quoteId,
				objectApiName: "Quote",
				actionName: "view"
			}
		});
	}

	/**
	 * Adds one day to a YYYY-MM-DD date string without timezone drift.
	 * Returns YYYY-MM-DD.
	 */
	addOneDay(yyyyMmDd) {
		const d = new Date(yyyyMmDd + "T00:00:00Z");
		d.setUTCDate(d.getUTCDate() + 1);
		return d.toISOString().slice(0, 10);
	}

	readError(error) {
		if (error?.body?.message) return error.body.message;
		if (error?.message) return error.message;
		return "An unexpected error occurred.";
	}

	toast(title, message, variant) {
		this.dispatchEvent(
			new ShowToastEvent({ title, message, variant })
		);
	}
}
